### PR TITLE
rename array_get() to Arr::get(), array_get() doesn't work in laravel 6

### PR DESCRIPTION
**Pull request by arisdevx**
Please approve this one

### CODE REVIEW

**Comment by dustingraham** [comment]
The errors appear to be for unit tests, but we don't have any unit tests. This one is probably safe to merge but I have not tested it myself.

Arisdevx, I presume you have tested this?

**Comment by dustingraham** [comment]
I guess my secondary testing is, how far back is Arr::get supported in laravel? Is it backwards compatible to Laravel 5.0?

**Comment by arisdevx** [comment]
Screenshot 2019-09-05 at 8 26 05 AM

this is error message when using array_get() in laravel 6.

I think it supports with version 5.7 or higher.

**Comment by dustingraham** [comment]
Ok, we may need to bump a minor rev number and update minimum support to 5.7

Merging this now will break existing implementations in the wild.

**Comment by arisdevx** [comment]
I think so or do you have a better idea for this issue?

**Comment by winter-ice** [comment]
It support laravel5

https://github.com/laravel/framework/blob/262b813fc88810071f8282722a89eb5199cb398a/src/Illuminate/Support/helpers.php#L209

**Comment by winter-ice** [comment]
this helper function is just a wrapper

**Comment by dustingraham** [comment]
Thank you for sharing that laravel commit @winter-ice ! Very helpful. I'll get this merged.

**Pull request merged**
