### PR TITLE
add caption

### PR DESCRIPTION
**Pull request by cugrif**
Hi
I recently opened issue https://github.com/lavary/laravel-menu/issues/248 . Now i resolved it.
I created new type caption for menu items. The caption hasn't link, but has text only. Also it can be activated by children.

### CODE REVIEW

**Comment by cugrif** [comment]
@dustingraham ok. I removed caption() method and changed naming for option.

**Comment by dustingraham** [comment]
Thank you, this looks great! `disableActivationByURL` is a good name.

Can you add a note to the documentation about this parameter? Perhaps near the bottom of this section:

https://github.com/lavary/laravel-menu#active-item

**Comment by cugrif** [comment]
@dustingraham  check please

**Comment by dustingraham** [comment]
Looks great!

**Pull request merged**
