### PR TITLE
Adds Laravel 5 Compatibility

### LINKED ISSUE #52: L5 compatibility
Are there any plans to make this package compatible with L5? (Assuming it's not already)

### PR DESCRIPTION
**Pull request by benswinburne**
Laravel 4 and 5 Service Providers included and correctly loaded depending on the version of Laravel.

Fixes #52.

### CODE REVIEW

**Comment by od3n** [comment]
+1

**Comment by chaosfinity** [comment]
Laravel 5.1 breaks this again by changing the blade extensions. 

They removed BladeCompiler::createPlainMatcher and Blade::createMatcher and made a BladeCompiler::directive($name, $handler) for creating a match

**Comment by dustingraham** [comment]
Should this be closed then?

**Comment by dustingraham** [comment]
Closing due to inactivity, and significant out-of-sync with master.

**Pull request closed without merging**
