### PR TITLE
Support for Laravel 5

### PR DESCRIPTION
**Pull request by nickurt**
Added support for Laravel 5, it needs also

    composer require "illuminate/html": "5.*"

for the html components

### CODE REVIEW

**Comment by fredrkr** [comment]
Did you test that you can affect laravel-menu's behaviour by changing values in the config files with this PR? Because I can't. The loadConf-method in Menu.php (line 54) does this:
```php
$options = \Config::get('laravel-menu::settings');
```
... and that apparently returns null. This means that laravel-menu proceeds as if no config options are given.

**Comment by lexpochta** [comment]
@fredrkr you are right. I just faced with the same issue.
It can be solved by adding the following code to `vendor/lavary/laravel-menu/src/Lavary/Menu/ServiceProvider.php` after line 28:
```php
if (file_exists($menuPath = app_path('Http/navigation.php'))) {
    require_once $menuPath;
}
```

So all `boot` method looks like this:
```php
/**
 * Bootstrap the application events.
 *
 * @return void
 */
public function boot()
{
    if (method_exists($this->app['config'], 'package')) {
        $this->app['config']->package('lavary/laravel-menu', __DIR__ . '/../../config');
    } else {
        $settings   = $this->app['files']->getRequire(__DIR__ .'/../../config/settings.php');
        $views      = $this->app['files']->getRequire(__DIR__ .'/../../config/views.php');
        $config     = array_merge($settings, $views);
        $this->app['config']->set('lavary/laravel-menu::config', $config);
    }

    if (file_exists($menuPath = app_path('Http/navigation.php'))) {
        require_once $menuPath;
    }

    // Extending Blade engine
    require_once('Extensions/BladeExtension.php');
}
```
And routes should be defined in `Http/navigation.php` instead of `Http/routes.php`

**Comment by fredrkr** [comment]
Instead of jerry-rigging this PR with workarounds, I would suggest using one of the two other PRs that adds L5 support: #57 or #58. #57 has been working for me thus far.

Of course, the best thing would be if the project owner would add L5-support him-/herself.

**Comment by nickurt** [comment]
Yep, L51 is integrated. /closed

**Pull request closed without merging**
